---
ID: "653535b1-da78-4810-8b1f-14af82ee5e41"
Parent: "3a5081e7-12d5-4a8d-a7eb-ffe33a04679c"
Template: "52288e39-7830-4694-b62d-32a54c6ef7ba"
Path: /sitecore/content/Basic Company Headless/Basic Company Headless/UK/Presentation/Placeholder Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220827T223516Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d38f13fb-1960-4f2c-8095-21a6e30e66e4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220827T223516Z
